# Generated by Django 4.2.2 on 2023-06-17 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_list", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datetime",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
