# Generated by Django 4.2.2 on 2023-06-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_list", "0003_alter_task_datetime_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datetime",
            field=models.DateTimeField(),
        ),
    ]
