# Generated by Django 4.2.2 on 2023-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_list", "0005_alter_task_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
