# Generated by Django 4.2.2 on 2023-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_list", "0006_alter_task_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
