# Generated by Django 4.2.2 on 2023-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_list", "0007_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
